[project]
name = "example-sqla-association_proxy"
version = "0.1.0"
description = "SQLAlchemy Association Proxy Example."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "flask-admin[sqlalchem-with-utils]",
]

[tool.uv.sources]
flask-admin = { path = "../../", editable = true }
